version: 0.0
Resources:
  - TargetService:
      Type: AWS::EKS::Service
      Properties:
        ClusterName: "my-cluster"  # Must match exact EKS cluster name
        Namespace: "default"       # Kubernetes namespace
        ServiceName: "brain-tasks-service"  # Your K8s Service name
        Image: "346701285224.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app-repo:latest"  # Full ECR URI

Hooks:
  BeforeInstall:
    - Location: "scripts/before_install.sh"
      Timeout: 300
      RunAs: "root"
  AfterInstall:
    - Location: "scripts/after_install.sh"
      Timeout: 300
      RunAs: "root"
  ApplicationStart:
    - Location: "scripts/start_application.sh"
      Timeout: 300
      RunAs: "root"
  ValidateService:
    - Location: "scripts/validate_service.sh"
      Timeout: 300
      RunAs: "root"
