version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 346701285224.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 346701285224.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app-repo:latest
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 346701285224.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app-repo:latest
      - echo "Configuring EKS access..."
      - aws eks update-kubeconfig --name my-cluster --region ap-south-1
      - kubectl config current-context
      - kubectl get nodes
      - echo "Deploying to EKS..."
      - kubectl apply -f deployment.yaml
      - kubectl rollout status deployment/brain-tasks-app-deployment

artifacts:
  files:
    - appspec.yml
    - deployment.yaml
    - service.yaml
