version: 0.2

phases:
  pre_build:
    commands:
      # Install kubectl (latest stable version)
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      
      # Configure AWS CLI
      - aws configure set region ap-south-1
      
      # ECR Login
      - aws ecr get-login-password | docker login --username AWS --password-stdin 346701285224.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 346701285224.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app-repo:latest

  post_build:
    commands:
      # Push to ECR
      - docker push 346701285224.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app-repo:latest
      
      # EKS Authentication
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --name my-cluster --region ap-south-1 --role-arn arn:aws:iam::346701285224:role/codebuild-my-app-codebuild-service-role
      - kubectl config view --minify
      - kubectl config current-context
      
      # Verify Access
      - kubectl get nodes
      
      # Deploy
      - kubectl apply -f deployment.yaml
      - kubectl rollout status deployment/brain-tasks-app-deployment --timeout=300s
      - kubectl get svc brain-tasks-app-service

artifacts:
  files:
    - appspec.yml
    - deployment.yaml
    - service.yaml
