apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app
    spec:
      containers:
      - name: brain-tasks-container
        image: 346701285224.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app-repo:latest
        ports:
        - containerPort: 80
